export enum ProductType {
  COOKIES = "cookies",
  CAKES = "cakes",
  BREADS = "breads",
  BIBINGKA = "bibingka",
}
export const cookiesProducts = [
  {
    id: "cookies_chocolate_chip",
    name: "Chocolate Chip",
    price: 12,
    image: "/cake7.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
  {
    id: "cookies_oatmeal_raisin",
    name: "Oatmeal Raisin",
    price: 12,
    image: "/cake2.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
  {
    id: "cookies_macadamia_nut",
    name: "Macadamia Nut",
    price: 12,
    image: "/cake4.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
  {
    id: "cookies_double_chocolate",
    name: "Chocolate",
    price: 12,
    image: "/cake7.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
  {
    id: "cookies_matcha",
    name: "Matcha",
    price: 12,
    image: "/cake7.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
  {
    id: "cookies_red_velvet",
    name: "Red Velvet",
    price: 12,
    image: "/cake7.webp",
    quantity_of_set: 1,
    type: ProductType.COOKIES,
  },
];
export const bakeryProducts = [
  {
    id: "cookies",
    name: "Cookies",
    price: 12,
    flavours: [
      "Chocolate Chip",
      "Oatmeal Raisin",
      "Macadamia Nut",
      "Chocolate",
      "Matcha",
      "Red Velvet",
    ],
    quantity_of_set: 1,
    image: "https://unsplash.it/200/200?image=1010",
    type: ProductType.COOKIES,
  },
  {
    id: "cake_rings",
    name: "Cake Rings",
    price: 18,
    flavours: [],
    quantity_of_set: 6,
    image: "/cake2.webp",
    type: ProductType.CAKES,
  },
  {
    id: "bibingka_muffins",
    name: "Bibingka Muffins",
    price: 15,
    flavours: [],
    quantity_of_set: 6,
    image: "/cake4.webp",
    type: ProductType.BIBINGKA,
  },
  {
    id: "breads_pandesal",
    name: "Pandesal",
    price: 10,
    flavours: [],
    quantity_of_set: 12,
    image: "/cake2.webp",
    type: ProductType.BREADS,
  },
  {
    id: "breads_brioche_tarts_4",
    name: "Brioche Tarts",
    price: 9,
    flavours: [],
    quantity_of_set: 4,
    image: "/cake4.webp",
    type: ProductType.BREADS,
  },
  {
    id: "breads_brioche_tarts_8",
    name: "Brioche Tarts",
    price: 17,
    flavours: [],
    quantity_of_set: 8,
    image: "/cake7.webp",
    type: ProductType.BREADS,
  },
  {
    id: "breads_brioche_rolls_4",
    name: "Brioche Rolls",
    price: 8,
    flavours: [],
    quantity_of_set: 4,
    image: "/cake2.webp",
    type: ProductType.BREADS,
  },
  {
    id: "breads_brioche_rolls_8",
    name: "Brioche Rolls",
    price: 16,
    flavours: [],
    quantity_of_set: 8,
    image: "/cake7.webp",
    type: ProductType.BREADS,
  },
];
